### ISSUE TITLE
"Special Power" Suggestions

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#1]
Some ideas:
- a feature that add elemental (fire, cold, electricity, etc.) damage to attacks. :heavy_check_mark:
- a feature that debuffs enemies on attack (something similar to crippling strike). ❗ 
- a feature that quickens all spells (probably needs some per day limit). :heavy_check_mark: (reworked)
- a feature that buffs summoned monsters :heavy_check_mark: (added in 1.1.0)
- a feature that increases character encumbrance :heavy_check_mark: (reworked to OP ability in 1.6.0)
- a second background selection :x: (Cannot implement this due to background limitations)

**Comment by Nerin3** [comment]
Start Isekai Protagonist with only Sorcerer Spell List and add other Spell Lists through Character Development Feats in training Arcs. 
Make him Arcane caster, but add a feat that negates spell failure in training arc.
