### ISSUE TITLE
Villain - Studied target

### ISSUE THREAD

**Issue by Mythalar** [JohN100x1/WOTR_IsekaiMod#100]
More of a question I guess.

As of now using Studied target does not increase DC for the Villain spells (or I could not see it), which would be the main use.

If it's indeed a bug can it be fixed?
If not I wonder what could duplicate this kind of effect (will look into this!)

**Comment by JohN100x1** [comment]
The studied target feature is actually completely copied from the Slayer class, so it works as far as the base game intends. Since the original Slayer class doesn't cast spells, maybe that's why it doesn't apply to spells.

**Comment by Mythalar** [comment]
Yes you are right. 

I find it not very useful as it is, but that's probably because I only ever make caster PC (and since it does read "and DC" in the tooltip...x) )

**Comment by JohN100x1** [comment]
I will consider reworking all the subclasses in a 5.0.0 version. I'll think about making new features that might be more useful for the villain then.

**Comment by Mythalar** [comment]
Well I guess it could be actually very much useful, notably for bosses, if it could be applied by spells and the DC part was effective.

**Comment by Mythalar** [comment]
Ok I just had an epiphany : why would you not replace studied target with Witch hexes?
They are INT scaled and can be used for quite a variety of things build-wise.

The base witch progression, or this one : first at lvl 1, one more at every odd level with Major hex at lvl 9 and Grand hex at lvl 17 with 2 at lvl 19(-1 hex overall but upgraded ones sooner).

**Comment by Mythalar** [comment]
With [Conduit Surge](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Conduit+Surge) that would be quite perfect.
