### ISSUE TITLE
Some vague ideas that you might like

### ISSUE THREAD

**Issue by Necht** [JohN100x1/WOTR_IsekaiMod#101]
Hi! Your mod is amazing and its potential is truly huge! I have some ideas that may be very curious. I didn't know which branch to write them to, so I made a separate post.

1. Make most skills on and off. This is especially true of the AutoQuicken and other.

2. Make Killing Intent an aura that can be turned off or that it acts on everyone for 4 rounds always

3. Make the Hero more heroic? I don't know what I can add here yet, but right now it doesn't look special enough. (I love this archetype).

4. Change the paladin's legacy. The paladin's legacy looks very superfluous and weak compared to others. Especially if you play as a Legend. Maybe you can change this legacy by removing everything from it that is now, and instead add all the auras of the paladin and all his archetypes? This can also be done as another legacy only for the hero and, if you want, you can call it a "Light in the Dark".

5. Please, make a choice in the fashion settings, how the basic clothes of this class will look like.(I don't like the current version and I can't change it). I would prefer basic paladin or warrior class clothing. I think it will add more roleplay.

6. More detailed description and artistic narration. It looks too dry right now.

7. What do you think about translating into another language?

7. New Animal Companion. Lawful Good Dragon.
The Deathsnatcher is funny, yes, but he's chaotic evil monstrous. Therefore, I suggest adding a new animal companion - a Lawful Good Dragon (who is in the likeness of Jharsygax). It can be as unbalanced as the Deathsnatcher, but for good heroes. Its features are the free change of its own size, from miniature (to sit on your shoulder or hide in your palms) to colossal. He should have huge physical stats in his true colossal form, but the physical characteristics should seriously decrease when his size differs from the true one. And the smaller its size, the more these stats will be reduced. This is for balance and RP. Mental characteristics should not change.

I would be very glad if you would add all this.

P.S. I apologize for any mistakes in the text, English is not my native language.

**Comment by kjk001** [comment]
reagarding 6:
At least for the features added by me I welcome any and all suggestions for artistic changes to descriptions or names. Mke your suggestion, we will at a minimum consider it.
regarding 7:
If you want to do the translation work we will certainly add the translation and John is highly likely to credit you for it(if only so he can blame you for it if it is bad).
regarding 8:
There is another Mod that adds dragon companions and we are compatible to it, so you can get your gold dragon that way.

**Comment by JohN100x1** [comment]
> 1. Make most skills on and off. This is especially true of the AutoQuicken and other.

Which skills specifically?

> 2. Make Killing Intent an aura that can be turned off or that it acts on everyone for 4 rounds always

I can make it into a toggle ability.

> 3. Make the Hero more heroic? I don't know what I can add here yet, but right now it doesn't look special enough. (I love this archetype).

We can discuss how to improve the Hero here (#102).

> 4. Change the paladin's legacy. The paladin's legacy looks very superfluous and weak compared to others. Especially if you play as a Legend. Maybe you can change this legacy by removing everything from it that is now, and instead add all the auras of the paladin and all his archetypes? This can also be done as another legacy only for the hero and, if you want, you can call it a "Light in the Dark".

I think @kjk001 should decide what to do with this Legacy.

> 5. Please, make a choice in the fashion settings, how the basic clothes of this class will look like.(I don't like the current version and I can't change it). I would prefer basic paladin or warrior class clothing. I think it will add more roleplay.

I can add UMM setttings to change base class clothing.

> 6. More detailed description and artistic narration. It looks too dry right now.

Can you explain with examples? I'm not much of an artist.

> 7. What do you think about translating into another language?

If someone wants to translate, it will be a [very long process](https://github.com/JohN100x1/WOTR_IsekaiMod/blob/master/IsekaiMod/Localization/LocalizationPack.json). We also maintain it when new content is added, so some-one who wants to create localisation can do so but they need to regularly contribute.

> 8. New Animal Companion. Lawful Good Dragon.
The Deathsnatcher is funny, yes, but he's chaotic evil monstrous. Therefore, I suggest adding a new animal companion - a Lawful Good Dragon (who is in the likeness of Jharsygax). It can be as unbalanced as the Deathsnatcher, but for good heroes. Its features are the free change of its own size, from miniature (to sit on your shoulder or hide in your palms) to colossal. He should have huge physical stats in his true colossal form, but the physical characteristics should seriously decrease when his size differs from the true one. And the smaller its size, the more these stats will be reduced. This is for balance and RP. Mental characteristics should not change.

I am not considering a new animal companion as this time. It is a long process to do so. When other features have been addressed, I can add something like this in the future.

**Comment by kjk001** [comment]
I was considering buffing the rogue legacy and then following that potentially the paladin, dread lord, and barbarian.

The base of the idea is currently being tested on the warrior legacy and should make things easier for us in the future when it comes to supporting different base classes and archetypes.

I was not going to go as far as adding every feature from every archetype though, only all of the base class...
The archetypes would then still be a second legacy.

**Comment by Necht** [comment]
Thanks! I'll write more now.

1. All of whom it would be more or less logical or by rp.
1.1 All Summoning.
You can choose how strong a creature you summon depending on your buffs.
1.2 Exceptional Weapon
1.3 Spell Negation
1.4 Magical Amplification
1.5 Reflect
1.6 AutoQuicken and maybe others


2. Yes, that's exactly what I was talking about!

3. I'll think about how I can help.

4. Paladin and his archetypes have a approximately of only 8 auras. I think it's not strong for legacy, but you can leave them together with True Smite.

5. That would be good!

6. A small example:
 Instead "Supreme Being: All your attributes have a base value of 30.", write 
 
"Your body has changed irrevocably, becoming something more than it was, but at the same time something less. Your muscles have hardened, become more elastic and stronger than a living being can have. Your mental component is vast and complex. Time no longer has power over you and you cannot grow old and die of old age.

Now you understand how fragile and naive you were. Now you have surpassed who you were. Now you cannot be called anything other than a Higher Being.

All your attributes have a base value of 30."

or something like that. 

7. I'm not a programmer and I don't know how to do it correctly. But I might try to help with the translation someday. But that's later.

To translate a text, you just need to insert a translation instead of the word "null"?

"{
  "LocalizedStrings": [
    {
      "Key": "d08e93950df84738a6bdb4969c0e791b",
      "SimpleName": "$IsekaiProtagonistSpellbook.Name",
      "ProcessTemplates": true,
      "enGB": "Isekai Protagonist",
      "ruRU": null,
      "deDE": null,
      "frFR": null,
      "zhCN": null,
      "esES": null
    },"
    
    8. Got it.
    
    P.S. I noticed about Martial Artist does not work with nunchucks.
    P.S.S. Maybe I'll help with something else later. But it is difficult to write a literary text not in your native language.

**Comment by JohN100x1** [comment]
> 1. All of whom it would be more or less logical or by rp.
1.1 All Summoning.
You can choose how strong a creature you summon depending on your buffs.
1.2 Exceptional Weapon
1.3 Spell Negation
1.4 Magical Amplification
1.5 Reflect
1.6 AutoQuicken and maybe others

The exceptional Summoning and exceptional weapon feats are already toggle abilities, same for `AutoQuicken` and the other auto magics. The only ones listed that are not toggle abilities are `Magical Amplification` and `Reflect`.

> 6. A small example:
    Instead "Supreme Being: All your attributes have a base value of 30.", write
>
> "Your body has changed irrevocably, becoming something more than it was, but at the same time something less. Your muscles have hardened, become more elastic and stronger than a living being can have. Your mental component is vast and complex. Time no longer has power over you and you cannot grow old and die of old age.
>
> Now you understand how fragile and naive you were. Now you have surpassed who you were. Now you cannot be called anything other than a Supreme Being.
>
> All your attributes have a base value of 30."
>
> or something like that.

I understand. This will take some time though, because I'm not very creative 😅

> 7. I'm not a programmer and I don't know how to do it correctly. But I might try to help with the translation someday. But that's later.
>
> To translate a text, you just need to insert a translation instead of the word "null"?
>
> "{
"LocalizedStrings": [
{
"Key": "d08e93950df84738a6bdb4969c0e791b",
"SimpleName": "$IsekaiProtagonistSpellbook.Name",
"ProcessTemplates": true,
"enGB": "Isekai Protagonist",
"ruRU": null,
"deDE": null,
"frFR": null,
"zhCN": null,
"esES": null
},"

Yes exactly. There's alot to translate and update.

**Comment by Necht** [comment]
> 
> I understand. This will take some time though, because I'm not very creative 😅
> 

Maybe I can help with that. In theory, I can write a whole short story and descriptions of all abilities so that the descriptions are combined with each other. But it certainly won't be this month.

I used to be fond of writing short stories and analyzing works of fiction and their characters. But if you find someone who does it professionally, it would be very cool!
