### ISSUE TITLE
Favorful OP ability feature descriptions

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#105]
Some of the features and abilities are not favorful and only describe what they functionally do. This Issue is to address improvements to the Overpowered ability descriptions.

References:
- #101

**Comment by JohN100x1** [comment]
Description for `Overpowered Ability — Unlimited Power`:
> On the brink of defeat the enemies have surrounded and exhausted you.
Just as they are about to deliver the finishing blow, you get up and saying the following words: Not today.
>
> Benefit: As a free action, you restore all abilities and spell slots.

**Comment by Nerin3** [comment]
> Description for `Overpowered Ability — Unlimited Power`:
> 
> > On the brink of defeat the enemies have surrounded and exhausted you.
> > Just as they are about to deliver the finishing blow, you get up and saying the following words: Not today.
> > Benefit: As a free action, you restore all abilities and spell slots.

I have a simple alternative for you, choose which one you prefer:
> On the brink of defeat the enemies have surrounded and exhausted you.
> Just as they are about to deliver the finishing blow, you get up and saying the following words: Playtime's over.

**Comment by Nerin3** [comment]
`Supreme Being?`
> You have transcended the limits of your original world and become a god among mortals. Your power is unmatched, your wisdom is infinite, and your charisma is irresistible. You are the Supreme Being, the ruler of all creation, the master of life and death. Nothing can stand in your way, nothing can challenge your authority, nothing can escape your judgment. You are the ultimate being, the one who will shape the destiny of this new world according to your will. All who oppose you will kneel before you or perish in your wrath. All who serve you will be rewarded with your grace and favor. All who worship you will be blessed with your miracles and wonders. You are the Supreme Being, and this world is yours to conquer.

**Comment by Nerin3** [comment]
You have discovered a secret skill that allows you to create gold out of thin air. You can use it to buy anything you want, from weapons and armor to food and clothes. You can also use it to bribe, impress, or intimidate anyone you meet. You are the richest person in this world, and no one can stop you. You are the king of wealth, the master of money.

**Comment by Nerin3** [comment]
`Infinite Space`
> It’s like having an inventory in a game, but better! No more worries about carrying heavy luggage, running out of supplies, or hiding your loot from greedy eyes. You can even store living beings, such as your harem of beautiful girls, or your loyal pet dragon. Just be careful not to lose track of what you have stored, or you might end up forgetting something important… like your original world.

**Comment by Nerin3** [comment]
@Necht I'm sorry, but I also disagree with you. Flavour text is flavour text. It's described from 2nd person perspective, so it doesn't represent the alignment of your character, but the person who's granting you the ability. Besides some of the flavour text in pathfinder is even worse in that regards.

**Comment by JohN100x1** [comment]
@Necht @Nerin3 I'm also sorry, but I also disagree with both of you. Feels a bit too long, but maybe that's just my preference. Here's my version (I hope it's not too dry):
> You have forgotten the hardships of mortality and what sort of person you were before. Were you stupid? Were you weak?
It matters no longer. Here in this new world, you are perfect.

**Comment by JohN100x1** [comment]
Description for `Meta Luck`:
> Everyone mistakes you for a prodigal genius, treating every action you make as part of your 1000 year plan. Enemies tremble in fear as meet you, hallucinating a universe-sized gap between them your power level.
\nBenefit: You always take the higher of two d20 rolls. Enemies that attack you take the lower of two d20 rolls for one round.

**Comment by JohN100x1** [comment]
Description for `Dupe Gold`:
> In this new world, you will never be cold or hungry again.
\nBenefit:As a standard action, you gain 1 million gold.

**Comment by JohN100x1** [comment]
![图片](https://user-images.githubusercontent.com/16169515/227722803-8d9b051d-f7bb-4c20-9958-31d98f1c1e9b.png)

**Comment by JohN100x1** [comment]
Description for `Summon Calamity`:
> There is nothing you cannot summon. Your commands are absolute; your calls are heeded. Even demon lords show no negligence... and tremblingly obey.
\nBenefit: As a full action, you summon a powerful being to bring calamity. You can summon one of the following: Devastator, Playful Darkness, Baphomet, Deskari, Nocticula, Mephistopheles, or Areshkagal.

**Comment by JohN100x1** [comment]
Description for `Perfect Roll`:
> You navigate every conversation and fight with perfect accuracy. Every word is predicted; every action is foreseen. Your premonitions guide you on your quest, as if you have experienced this before...
\nBenefit: You always {g|Encyclopedia:Dice}roll{/g} a 20 on all d20 rolls.

**Comment by JohN100x1** [comment]
Description for `Mind Control`:
> Behold the power of a king! All will listen and obey!
\nBenefit: You can make any creature fight on your side as if it was your ally. It will {g|Encyclopedia:Attack}attack{/g} your opponents to the best of its ability.

**Comment by JohN100x1** [comment]
Description for `Instakill`:
> Who will live and who will die? This power to change fate lay within your hands. Will you use this power sparingly? Or will you become god of the new world?
\nBenefit: Kills the targeted creature if they fail a DC 99 fortitude saving throw, otherwise they are stunned for 1 round. This ability bypasses death immunity.

**Comment by Nerin3** [comment]
Isn't it a little too long tho?

**Comment by JohN100x1** [comment]
You got me there. Normally yes, I believe a few impactful words would leave a more powerful impression on the reader.
But in this case I was inspired by your initial proposal for `Infinite Space` and I thought it would be funny to make it into a sales pitch. Some parts of it was AI generated though which didn't really take into account sentence length.
