### ISSUE TITLE
Few additional Archetype Ideas

### ISSUE THREAD

**Issue by Nerin3** [JohN100x1/WOTR_IsekaiMod#11]
**Villain:**
Instead of being reincarnated as a good guy you're reincaranted as a Villain.

Uses Intelligence instead of Charisma for spells, memorizes spells instead. 
Instead of a Training Arc abilities gains a second overpowered ability at the beginning.
Loses True Main Character, but gains Second Form.
Dark Aura similar to God Emperor
Loses half of the Sneak attack but gains Studied Target of Slayer
Second Form: After being reduced to 0 HP resurrects with Full HP, one size category bigger and with temporary boosts to all statistics. Once per rest.

**Avatar:**
Loses Sneak Attack and spellcasting but gains Kineticist abilities instead
Can choose a new blast every 2 levels, to a maximum of 8 

**Tag along** (Could be a separate class as well with similar archetypes but weaker):
Not a true protagonist per say. They've gotten summoned alongside the isekai protagonists, at least that is what they think so.
No initial overpowered ability, additional training arc abilities
Doesn't have any sneak attack abilities or spellbook, but can unlock many abilities of isekai protagonists as training arc feats.
Maximum level 40 without the need of becoming a legend.
Loses True Main Character in favor of an overpowered ability instead.

**Comment by JohN100x1** [comment]
villain sounds like an excellent idea. I'll schedule this for 1.4.0

I'll need more details for avatar though, it sounds like it could work but I'll need a description for this archetype for it to fit in with the original idea of the class.

tag along sounds like it'll take a lot of work to do, first because I think it should be implemented as a separate class but also figuring out how to increase the maximum level. I think a more balanced version of the `Isekai Protagonist` is a good idea, but I won't implement this for now because balancing and playtesting a class takes alot of time.

**Comment by Nerin3** [comment]
Avatar(it's a working title) is a kineticist version of isekai protagonist that instead of spellcasting has mastery over every blast instead of 3 blasts only (like a normal kineticist).

**Comment by JohN100x1** [comment]
I understand the mechanics, I was just wondering if you had any ideas for a description (or ideas for what to put on the archetype description).

e.g. "Some protagonists choose to be reborn with kinetic abilities rather than magic..."
Or "Due to their traumatic experiences in their past life, they gain violent kinetic abilities..."

Now that I think about it, i might have answered my own question 😄

**Comment by Nerin3** [comment]
Oh I've got two additional ideas for 2 archetypes:

Maou - Only for Tieflings (Would work great with any heritages your planning)L

Keeps Charisma for casting
Gets Sorcerer's Abyssal or Infernal bloodline for free. 
His abilities and spells focus mostly on summons and commanding, that's why he loses sneak attack completely, but gains powerful auras that boost his summons and allies.
Loses Character Development feats completely.
Gains druid wildshape but gets demons as wildshape forms instead.
Sacrifice - Replaces True Main Character, Whenever Maou is about to die one of his companions dies in his stead. Maou regains HP equal to to maximum hp of the companion and gains boost to all his stats equal to 1/4 of the companion level.



Hero - For other races:

More Paladin like version of Isekai Protagonist,
Is a divine caster.
Gets paladin abilities, but loses sneak attack (What kind of hero fights dirty)
Gets True Smite ability (can affect any creature regardless of its alignment)
Hero's Aura:
A 20th level ability that replaces True Main Character.
Everyone within aura cannot be reduced under 1HP except of the Hero. Everyone gains 10 spell resistance and 20 DR/Evil.


It's a bit of a mess but it's more of a bunch of overall ideas, feel free to use them however you want or not at all.

**Comment by JohN100x1** [comment]
thanks! these sound like great ideas. very thematic. I'll consider them for a later update.

**Comment by Darkfire11** [comment]
Porting over the "Mary Sue" idea for your consideration.

Proficiencies: Same as Edge Lord, but renamed "Mary Sue proficiencies".

Remove Training Arc and Character Development.  The Mary Sue is a flat character and does not train or undergo character development.

Remove Beach Episode, which doesn't really apply to Mary Sues.  Instead Harem Magnet is obtained at level 12 and renamed "Stud Farm."  Same feat description.

Pet must be Black Horse or Horse, but gains the Celestial type (from Divine Hunter archetype).  Ideally this would be a white horse with a horn and called "Unicorn", but that's probably more trouble to implement than it's worth.

Gain +1 bonus to Diplomacy every level.

Gain "Beautiful Combat" at level 1.  The Mary Sue uses Charisma for hit and damage rolls.

Gain "Beloved by All" at level 2.  The Mary Sue gains an inherent bonus to Charisma equal to half her character level.

Gains "Divine Grace" at level 3.  Just repurpose the same feat from Paladins.

Gain "Power of Friendship" at level 5.  Increases DC for Enchantment spells by +2, increasing by another +2 every five levels.  Stacks with Spell Focus feats, of course.

Gain "Really Determined" at level 7.  Increases spell penetration by +2.  Further +2 increases at levels 13 and 19.

Gain "Otherworldly Beauty" at level 17.  This is just the Trickster Rank 3 Perception Mythic Trick.  Enemies would rather off themselves than lay a finger on the Mary Sue.

Capstone ability is "Too Good for this World."  When the Mary Sue is reduced to 0 HP, she fully heals the rest of the party, including raising dead and restoring any lost attribute points or levels.  The party also gains Haste and +8 Sacred bonus to all attributes for the remainder of combat, whereupon the Mary Sue resurrects.  The Mary Sue is immune to further damage and cannot be raised until then.

**Comment by JohN100x1** [comment]
thanks for your idea. i'm holding off on adding any more archetypes at the moment after realising how much work it took. Right now i'm thinking about adding more feats for the existing class. When I get back to this i'll be sure to have a look.

**Comment by Darkfire11** [comment]
Understood.  Thanks for all your work on this mod!

**Comment by Nashinote** [comment]
I was thinking about archetype that can somehow implement rage powers and what came to mind were chuuni characters who had god/devil/dragon sealed in their hand/eye/leg/schlong. The concept being is that character unseals their power for brief moment using system similar to rage. Probably ditches sneak attack for rage powers and bloodline heritage, maybe different bonuses depending on the sealed appendage (unsealed hand will give bonus to attack rolls and claw attack for example) and/or the type of thing being sealed (god eye will shoot holy lasers, devil eye charms enemies as a gaze attack).
Though that might even deserve it's own class.

Another archetype is Beast of Gluttony/Predation that will borrow swarm-that-walks devour system to get various bonuses from eating enemies corpses. The inspiration obviously comes from characters like Rimuru from That time I was reincarnated as a slime and countless others.

**Comment by Nerin3** [comment]
I think you could change isekai vampire, drow grant INT instead of Charisma so they work better with villain. For Succubus it could be CHA and INT

**Comment by JohN100x1** [comment]
i'll change some stats for the heritages but i don't want fully remove CHA from drow or DEX from succubus

**Comment by Nerin3** [comment]
I just thought of this, so I'm leaving it here in case you'd ever want to implement something similar. 

Chuuni Archetype -
Doesn't have nornal spellcasting. Can only use illusion magic. Instead gets witch hexes and their shadow spells are (Evocation, Conjuration and Enchantment) 20% more real. Their shadow magic can also emulate cleric spells.

**Comment by JohN100x1** [comment]
New villain ability:
> "ENOUGH!" when the villain gets to half health, he AoE stomps everyone (could use the Vrock screech animations) and automatically stuns all creatures within 100 feet for 1 round (no save allowed). If the enemy is immune to stun, they are staggered instead. Happens once per encounter (or per day if you prefer). You decide if this is overpowered or special ability with villain requirement or if you want to add it baseline, although I think every self respecting villain have their "ENOUGH" moment.

([link](https://forums.nexusmods.com/index.php?showtopic=12204503/#entry119439248))
