### ISSUE TITLE
Neutral viability

### ISSUE THREAD

**Issue by ThePiggyGalaxy** [JohN100x1/WOTR_IsekaiMod#112]
Please make it so that neutral characters can pick options which are typically good or evil aligned like the channelling of positive and negative energy, since right now when I play a neutral character that's not really viable. Alternatively options to change / disable alignment restrictions for subclasses and / or selectable features.

**Comment by ThePiggyGalaxy** [comment]
I'll take a look and edit this when I find some

**Comment by kjk001** [comment]
Monk Legacies were already relaxed to also allow neutral alongside my last bugfix for some feats(capstones) being added twice after the logic was changed.

Sadly I underestimated how fast John would be with the merging and uploading, so that patch is now part of either 4.2.1 or 4.3.
