### ISSUE TITLE
Dual Legacy, through mythic feats, not working  for other classes

### ISSUE THREAD

**Issue by Wolfy339** [JohN100x1/WOTR_IsekaiMod#113]
- Choosing dual legacy through OP ability does nothing for the other classes, is it a bug?
- Mythic abilities though "extra mythic feats" are still selectable only once.

**Comment by JohN100x1** [comment]
> Choosing dual legacy through OP ability does nothing for the other classes, is it a bug?

I'm pretty sure that dual legacy should only be selected by the Isekai Protagonist class so that fact that you can select it as other classes is a bug.

> Mythic abilities though "extra mythic feats" are still selectable only once.

I'm not sure what you mean by this?

**Comment by kjk001** [comment]
yes Dual Legacy should most definitly only be available to IP itself.
The fact that it is available at all through the mythic selection is a mistake born from the fact that I had completely overlooked that they were added there.
The next patch will have a restriction to ensure you can only pick it if you have the class

**Comment by JohN100x1** [comment]
From the looks of it, there's a limit on how deep the selections can expand. I'm thinking to put the `Mythic Class Feature` outside of `Mythic Overpowered Ability` and into the `Mythic Ability` selection and see if that would fix it.

**Comment by kjk001** [comment]
yes that would be one of the two possible causes

**Comment by Wolfy339** [comment]
Also, thank you both for the hard work!

**Comment by JohN100x1** [comment]
I have changed the `Mythic Class Feature` to appear in the mythic ability selection directly rather than in `Mythic Overpowered Ability` and `Mythic Special Power`.

The `Mythic Class Feature` should still appear in the regular `Overpowered Ability` and `Special Power` selections on the isekai protagonist.
