### ISSUE TITLE
Background suggestions

### ISSUE THREAD

**Issue by ThePiggyGalaxy** [JohN100x1/WOTR_IsekaiMod#114]
In https://github.com/JohN100x1/WOTR_IsekaiMod/issues/111#issuecomment-1478197081 I suggested the following backgrounds as they seemed to fit with more varied worlds of origin than just our world.

- Scholarly sectarian: You used to be part of a scholarly faction of the murim of your old world, you used all your time acquiring knowledge but died before you could obtain all of it.
You can use the highest between your intelligence or your wisdom when you use knowledge, lore or perception checks and gain proficiency in these

- Demonic cultist: Before you died you used to practice demonic arts inside of the Demonic Cult of your previous world's murim, this made you quite aggressive, but helped you grow your strength quickly, however your increased aggression was likely the cause of your death
You can use the highest between your strength and dexterity for athletics and mobility check and gain a proficiency in these

**Comment by JohN100x1** [comment]
Cool. I will consider them for 5.0.0. I would probably change `demonic cultist` to `Demonic cultivator` just to make it sound more wuxia-like instead of sounding like the ordinary cultists we fight in the game.

I'll list any more changes here when I begin implementation.

**Comment by Nerin3** [comment]
If you want to keep it Murim instead of Wuxia, just use Heavenly Demon Divine Cult or Heavenly Sun-Moon Cult instead.

**Comment by ThePiggyGalaxy** [comment]
> If you want to keep it Murim instead of Wuxia, just use Heavenly Demon Divine Cult or Heavenly Sun-Moon Cult instead of Demonic Cult.

Yea, it is what I was going for, but a more generic `Demonic cultivator` would probably work better, after all, the more generic the flavor is the more creative you can be with it in your headcannon

**Comment by bundillion** [comment]
Logical Objectivist (maybe a bit specific) - Honestly, all of the "magic" and "demons" is starting to seem a bit crass. Certainly, there are some large and particularly hideous beings wandering about with talks of the Abyss, but everyone knows the only real danger there is staring too long. Anything else is the ludicrous fantasy of tattered minds sick from a century of war.
Wary of any failings in these obvious tricks, gain SR 9+INT, a +4 bonus to all saving throws against spells, and to all _dispel magic_ checks.

Sound Tech/Punk Rocker - At first it was a job, then it was a joy, and finally it became a jaunt into the wrong realm. After playing music a little too loud and falling into a sound-made rift in spacetime, it's your time to bring the noise to the Worldwound.
Gain +2 CL on all sonic magical effects, +4 to Persuasion checks, and double CHA when calculating the number of rounds of performance granted by any source.

idk if these are feasible programming-wise but they seem fun

**Comment by JohN100x1** [comment]
Here's the backgrounds I've implemented for 5.0.0 so far. Let me know your thoughts
- `Demonic Cultivator`: Adds athletics and mobility as a class skills. Use the higher of STR and DEX for these checks.
- `Enlightened Scholar`: Adds lore, knowledge, and perception skills as class skills. Use the higher of INT and WIS for checks.
- `Musician`: Adds Persuasion as a class skill. Has a +2 competence bonus to caster level for Sonic spells.
- `Rationalist`: Has Immunity to spell and spell-like abilities but cannot cast spells.

**Comment by Mythalar** [comment]
Rationalist is brutal live it ;)

Demonic cultivator and Enlightened Sage are nice and there is now quite some choice for skill check bas stats.

Musician is the only one I'm not fully convinced since sonic spells do not scale very much. Perhaps add/replace a bonus DC because they usually target fortitude which is often a high save?

**Comment by bundillion** [comment]
Rationalist might not be the most balanced tradeoff, although maybe just get perfect rolls ig

**Comment by ThePiggyGalaxy** [comment]
I really love them :D

I was worried about the feasibility of the higher of the two stats backgrounds but seeing it be implemented warms my heart
