### ISSUE TITLE
Reflect.. killing me?

### ISSUE THREAD

**Issue by mrdude217** [JohN100x1/WOTR_IsekaiMod#125]
**Describe the bug**
I was under the impression that reflect hurts the attacking enemy, but it seems to be hitting me.  The damage returned is divine as well.  

**To Reproduce**
I have celestial realm, and reflect. 

**Expected behavior**
Anybody damaging me to take that damage back to their face.

**Screenshots**
![image](https://user-images.githubusercontent.com/129306346/229874171-2eec60d0-cfda-45e8-bc4d-2d082190cee7.png)

**Additional context**
As far as I know none of these babaus actually hit me, so I'm reflecting my own divine damage back to myself?  Maybe? Idk

**Comment by JohN100x1** [comment]
I can add a check that would exclude the reflect owner. I haven't really thought about situations like these when I first made this ability.
