### ISSUE TITLE
[4.3.0] Monk Legacy - Fast Movement not applied to character

### ISSUE THREAD

**Issue by NightOwlByDay** [JohN100x1/WOTR_IsekaiMod#128]
**Describe the bug**
When using either the Daoist or Dragon Monk Legacy with the Isekai Protagonist, the "Fast Movement" Feature from the Monk Class gained at level 3 is not applied to the character (nor are the upgrades of the Feature that should be gained every 3 levels after the 3rd level).

**To Reproduce**
1. Create Human Isekai Character with one of the Monk Legacies
2. Level character to at least level 3.
3. Check Movement Speed on character sheet

**Expected behavior**
Movement Speed should be 40.
30 from base Movement Speed + 10 from Fast Movement Feature

**Screenshots**
![image](https://user-images.githubusercontent.com/130167830/230642683-7fe1159f-36fa-427b-a6cd-88b69bde7840.png)

**Comment by kjk001** [comment]
I will check on that, this is a contextrankconfig, so it should have worked

**Comment by kjk001** [comment]
and contextrankconfigs are only patched for abilities not pure features, good catch, will be fixed in 5.0
