### ISSUE TITLE
Bloodrager legacy unavailability main class

### ISSUE THREAD

**Issue by ThePiggyGalaxy** [JohN100x1/WOTR_IsekaiMod#135]
I saw that the base class currently doesn't have access to the bloodrager legacy, is this intended or not, because it's quite inconvenient. If intended please add a umm option or something allowing it for the base class

_Originally posted by @ThePiggyGalaxy in https://github.com/JohN100x1/WOTR_IsekaiMod/issues/131#issuecomment-1511984295_

**Comment by JohN100x1** [comment]
I made a [new release](https://github.com/JohN100x1/WOTR_IsekaiMod/releases/tag/5.0.1) to resolve this.
