### ISSUE TITLE
probably imposible suggestion

### ISSUE THREAD

**Issue by ssebaa** [JohN100x1/WOTR_IsekaiMod#139]
This mod is so amazing and it keeps becoming better, im having so much fun with the game now. Keep up the amazing work! Also i come up with a small idea, would it be possible to allow isekai protagonist class to have 40 levels? And when 21 level starts (when u pick up legend path) u can choose additional legacy? It's a lot of work probably and I even dont know if the game engine will allow for this but the feature itself would be quite fun i think ;)
Have a nice day!

**Comment by JohN100x1** [comment]
I haven't found a way to extend the class levels beyond 20. It's probably best to use a prestige class instead
- #132
