### ISSUE TITLE
Sorcerer Chimera Legacy aren't copying spell into spellbook as you level up

### ISSUE THREAD

**Issue by Lordjoseph7** [JohN100x1/WOTR_IsekaiMod#140]
As the title states, I get them under the abilities list, but they do not appear in my spell book. Fey Bloodline.

**Comment by Lordjoseph7** [comment]
There is also a similar issue with Aeon Spellbook when picked from the superweapon abilities. The spells are not being added to the Mastermind spell book.

**Comment by JohN100x1** [comment]
You closed this issue. Do you still have this issue?

**Comment by Lordjoseph7** [comment]
Sorry, I got confused and closed the issue. Glad you found the source of the problem.

**Comment by JohN100x1** [comment]
@kjk001 Looks like there was a bug when comparing references (using `.Equals` is prefered over `==`). You might want to check if there's any other logic which compares references.

I was able to add the fix in the new branch I created `hotfix_5-0-X`. Release for 5.0.3 should be later today.

**Comment by kjk001** [comment]
yeah I just noticed the screw up on my part luckily for the most part checks required a contains rather than an equals anyway so few places should be affected
