### ISSUE TITLE
Feat Ideas

### ISSUE THREAD

**Issue by Nerin3** [JohN100x1/WOTR_IsekaiMod#24]
Here are some feats that could work with Isekai Protagonist.
Master of All trades - Only on First Level
Before reincarnating you've spent most of your time on training, due to that you've achieved something that only few had, you've become master of all trades. +1 to DC of All Schools of Magic, +1 to DC of any elemental attack, +2 to Spell Penetration, +1 to Hit with any weapon and, +1 to damage with any weapon, +1 to AC (Dodge), +1 to AC if wearing any armor, +1 to AC if using a shield.
Loyal Friends - 
Members of your party roll with advantage against compulsion and charm effects.
Chimera - 
Nobody knows what floats through your veins, can choose any class or feats regardless of race restriction
Bloodline awakening - Can choose sorcerer's bloodline.
Mystery's Calling - Gain one of the Oracle's Mysteries. and its True Revelation at level 20.

**Comment by JohN100x1** [comment]
these sound interesting, i'll consider for a later update when i rework some things with the isekai protagonist class

**Comment by jedi7000nathan** [comment]
Starting weapon feats similar to the Exotic weaponry feats only difference is that they is allow you to get to choose the weapon you start the game with, only applies by the way for weapons you have proficiencies for that way the player can start with whatever weapon they want their Isekai to use.

**Comment by JohN100x1** [comment]
excellent idea. I remember I had to wait until finean to get the type of weapon I wanted.

**Comment by kjk001** [comment]
"Bloodline awakening - Can choose sorcerer's bloodline." not really feasible as a feat because similiar to the kineticist blast the sorcerer bloodline is a progression feature with class limitations, that means the class or archetype that is supposed to profit from it has to be patched into the progression and in the case of sorcerer bloodline also into each individual spell known grant given by said bloodline.
Therefore this has to be bound at a minimum to an archetype rather than a feat. Second Bloodline as a feat could then be added for that archetype though.
@Nerin3 so want to be the one to name the Isekai Archetype?

**Comment by Nerin3** [comment]
If I was the one to name such Archetype, I'd name it Chimera and allow it to pick up to 5 bloodlines over course of the progression.

**Comment by kjk001** [comment]
so first bloodline at level 1 then at level 5, 9, 13, and 18?
And something similiar for the Oracle Mysteries and shaman spirits?

I will change it so that for the selections past level 1 you get a choice between a bloodline or a bloodline feat, or the equivalent for the other classes.
@Nerin3 so descriptions for the new archetypes, and name and descriptions for those higher level selections please :)

**Comment by kjk001** [comment]
fun the curses are also level progressions, but the mysteries are normal blueprintfeatures with components of the type AddFeatureonClassLevel, so figuring out where and how the archetype has to be patched into them starts from 0...

On the upside sorcerer is done and works and only needs the flavortext

**Comment by Nerin3** [comment]
Chimera: 
Their otherworldly knowledge and point of view allows Chimeras to imbue themselves with different bloodlines in order to gain power and strength. The Chimera is constantly seeking out new sources of power, and their ability to absorb and incorporate these different bloodlines allows them to become truly formidable foes. However, their constant experimentation with bloodlines can also lead to confusion and uncertainty about their own heritage and identity, as their original ancestry becomes harder to discern over time.

Seeker of Truth:
Seekers of Truth are driven by a desire to uncover the secrets behind the fundamental forces of nature. Because of their unique perspective as otherworlders, they are able to approach the world with a fresh and unbiased eye, allowing them to see beyond the surface of things and seek out the deeper truth behind the world around them. They are driven by a desire to uncover the secrets of the world that would otherwise remain hidden, and are not satisfied with simply accepting things at face value. This allows them to uncover the secrets of the world that are often only revealed to mortals through revelations.

Spirit Beacons:
As a person who have originated from the other world Spirit Beacon has an unique aura. This aura is particularly attractive to spirits, and they have learned to harness the power of these spirits by forming contracts with them. Despite their reliance on spirits, Spirit Beacons are not bound by the will of these supernatural beings. They are able to maintain their independence and make their own decisions, using the power of the spirits as a tool rather than being controlled by them.

I guess that should be okay?

**Comment by kjk001** [comment]
Chimera and Seeker done and uploaded, ready for John to merge them into the main branch if he also likes them. 
Spirit Beacon will take a while as at least for now I am done with trying to figure out why every single class hast to have its own progression logic and why worst of all it has to be handed down to every single feature used in that class, then the components of that feature and the features referenced by those components, with an ever switching logic of if the class, archetype, or both should be referenced at each level.
