### ISSUE TITLE
Isekai Heritage Suggestions

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#3]
Some ideas:
- Isekai Succubus (Tiefling heritage) ✔️ (added in 1.5.0)
- Isekai Angel (Aasimar heritage) ✔️ (added in 1.5.0)

Looks like there's a WingsAngelBlack in the blueprints. Add this as a heritage skill?
Use the following links as a basis:
- https://www.d20pfsrd.com/bestiary/monster-listings/outsiders/demon/succubus/
- https://www.d20pfsrd.com/bestiary/monster-listings/outsiders/angel/

**Comment by Nerin3** [comment]
I guess there is always some Isekai with vampires, so Isekai Vampire?

**Comment by JohN100x1** [comment]
sounds good. this could be added in 1.8.0

**Comment by Nerin3** [comment]
There are few pair of demonic wings and angelic, so you could give player an option to choose between Normal succubus wings, mythic demonic wings or Aru's wings, and between Black & white angelic wings.

**Comment by JohN100x1** [comment]
arueshalae's wings are actually attached to the character rather than a separate entity. Having extra wings sounds like a good idea.

**Comment by jedi7000nathan** [comment]
A heritage of some kind for the Halflings I'm not sure what exactly but it would give them bonuses to offset their racial maluses and boost trickery and perception but also some other aspects something for the Halflings to throw them a bone.

**Comment by Nerin3** [comment]
High Human(from the New Gate) to show humans some love.

**Comment by kjk001** [comment]
@Nerin3 
What would be the abilities of a high human?
Based on the Wiki description it sounds a bit like a static +100 attribute buff on everything which might be a bit overpowered even for this mod...
