### ISSUE TITLE
Levelable Aivu

### ISSUE THREAD

**Issue by jedi7000nathan** [JohN100x1/WOTR_IsekaiMod#42]
Just a bit of a side thing: the mod Levelable Aivu broke recently and I was wondering if you could as a bit of an addon for the mod make her levels something you control as a player: just a bit of a thing for those of us who wish to play an Isekai Azata,

**Comment by JohN100x1** [comment]
this is not the direction i want to take the mod. I want to focus on new content rather than gameplay tweaks.

[looks like some guy was kind enough to update that mod (not merged yet though)](https://github.com/pheonix99/LevelableAivu/pull/10). You'll just have to wait until the author releases it.
