### ISSUE TITLE
The ability to get random items

### ISSUE THREAD

**Issue by jedi7000nathan** [JohN100x1/WOTR_IsekaiMod#44]
Basically an Overpowered ability similar to the gold one: only this one gives you random equipment, you could then divide this into various types of items with one ability for weapons, one for armor, one for any number of items such as support stuff. Basically this is an item version of duplicate gold. Another idea I've got involves some sort of random loot script similar to the ones used by Random Equipment and Worldcrawl where there is a chance to generate random loot on existing containers and corpses but one that actually works because both of those mods I've mentioned no longer work with the latest update and their creators have no intention of updating them, I'm just putting forth ideas whichever one of them you like let me know. Basically, it's to remove some of the monotony of loot in Wrath being the same and allow the Isekai to get excellent gear early on

**Comment by JohN100x1** [comment]
this doesn't sound like a good idea. after spamming the ability a bunch of times to get the item you want, it just basically becomes another way of getting gold if you sell the items, rendering the dupe gold ability obselete.

Alternatively, I think endgame items could be given as starting equipment based on the background / deity.
