### ISSUE TITLE
God Emperor and little things

### ISSUE THREAD

**Issue by Mythalar** [JohN100x1/WOTR_IsekaiMod#48]
Hey there !

Quite a blast so far with your mod so thans :)

So far I mainly use the God Emperor archetype since I like the progression mechanics but there is one thing bothering me : 
It's obviously very powerful but is quite missing some interesting things by not having any Character developement feats and less Overpowered abilities.

- In the end its immuned to damage, but a simple Isekai Protagonist cannot die either at lvl20
- Full ability scores bonuses can be granted sooner as an Isekai than as a God Emperor
- Less options concerning spellcasting (spellmaster is offset by sacred ability scores bonus and siphoning aura, but no Sneaky magic)
- No kineticist blast if one would want it
- No channel option
- No extra attack or such

Perhaps keeping the overpowered abilities and a reduced Character development feats list (since no need for energy immunities, bonus stats etc...), at initial rate, but halving base bonus feats ?

Some other points : 

- [Champion feats mod ](https://github.com/lynnpye/Champion-Feats) introduced scaling feats to AC/attacks//spell damage and DC, skills etc... so I guess it's closed to what you wanted for spells?
- I quite agree with the other post concerning the Villain casting issues : it would be nice to use the arcanist system instead of the wizard one
- [DarkCodex mod](https://github.com/Truinto/DarkCodex) added the Elemental Scion kineticist archetype, that allow some progression to blast damage and DC, at the cost of focusing on one element, so an isekai archetype based on it, but with the four elements, would be quite baddass (can work on a description if needed)

**Comment by JohN100x1** [comment]
Thanks for taking the time to write this feedback.

> So far I mainly use the God Emperor archetype since I like the progression mechanics but there is one thing bothering me : It's obviously very powerful but is quite missing some interesting things by not having any Character developement feats and less Overpowered abilities.

My idea for this archetype is that you buff allies early and later become more powerful. The lack of character development feats is to balance out how powerful it is.

> In the end its immuned to damage, but a simple Isekai Protagonist cannot die either at lvl20

I plan on reworking level 20 feature into something else. The problem with changing this is to find another powerful effect to replace it with.

> Full ability scores bonuses can be granted sooner as an Isekai than as a God Emperor

This is what I intended to balance out the class, because isekai protagonist becomes very powerful early but god emporer has higher potential. I think changing the `Training Montage` bonus to +8 would be sufficient.

> Less options concerning spellcasting (spellmaster is offset by sacred ability scores bonus and siphoning aura, but no Sneaky magic)
No kineticist blast if one would want it
No channel option
No extra attack or such
>
> Perhaps keeping the overpowered abilities and a reduced Character development feats list (since no need for energy immunities, bonus stats etc...), at initial rate, but halving base bonus feats ?

Because this archetype is so powerful, it needs to have less overpowered abilities and character development feats. Simply replacing bonus feats with the god emporer feats means the base class is strictly worse.
Here's my initial thoughts on how to rework the archetype:
- Remove `Fast Movement` and `Quick-Footed`.
- Remove all sneak attack.
- Reduce OP abilities from 3 to 2 OP (base class has 4).
- Increase character development feats from 0 to 3 from reduced list (base class has 5).

> [DarkCodex mod](https://github.com/Truinto/DarkCodex) added the Elemental Scion kineticist archetype, that allow some progression to blast damage and DC, at the cost of focusing on one element, so an isekai archetype based on it, but with the four elements, would be quite baddass (can work on a description if needed)

It took me a week to add all 4 kineticist blasts with their form infusions. This is because the blast progression, DC calculation, and wild talents were all highly coupled with the kineticist class so I had to re-create all the abilities. An archetype with kinetic blast will take multiple weeks so I will not be working on new archetypes at this time.

**Comment by Mythalar** [comment]
> > In the end its immuned to damage, but a simple Isekai Protagonist cannot die either at lvl20
> 
> I plan on reworking level 20 feature into something else. The problem with changing this is to find another powerful effect to replace it with.
> 
> > Full ability scores bonuses can be granted sooner as an Isekai than as a God Emperor
> 
> This is what I intended to balance out the class, because isekai protagonist becomes very powerful early but god emporer has higher potential. I think changing the `Training Montage` bonus to +8 would be sufficient.
> 
> > Less options concerning spellcasting (spellmaster is offset by sacred ability scores bonus and siphoning aura, but no Sneaky magic)
> > No kineticist blast if one would want it
> > No channel option
> > No extra attack or such
> > Perhaps keeping the overpowered abilities and a reduced Character development feats list (since no need for energy immunities, bonus stats etc...), at initial rate, but halving base bonus feats ?
> 
> Because this archetype is so powerful, it needs to have less overpowered abilities and character development feats. Simply replacing bonus feats with the god emporer feats means the base class is strictly worse. Here's my initial thoughts on how to rework the archetype:
> 
> * Remove `Fast Movement` and `Quick-Footed`.
> * Remove all sneak attack.
> * Reduce OP abilities from 3 to 2 OP (base class has 4).
> * Increase character development feats from 0 to 3 from reduced list (base class has 5).


All noted, removing Fast movement is only fair since a character delelopment feat can be used to mimic it.

For the rest I would personaly do something like : 

- 1/2 sneak attack (2/3 as of now?) since some enemies are immuned
- 3 OP same as now
- 2/3 (or even 1/2?) bonus feats
- 2 character development feats from reduced list (but not too late level wise)

And yeah I can see that kineticist stuff can be awful to mod ^^

**Comment by Mythalar** [comment]
So, after being quite some time in the character creation screen... !

Finally, perhaps what's the most bothering is just the progression pacing for this archetype, and not the access to certain feats.

Good thing is it could easily be fixed by backing more things in Nascent Apotheosis and less at the end, which makes sense (I guess), IE : 

- +1 spell penetration / 2 char levels (ignore SR and spell immunity at level 20),
- +3 resistance energy / char level (on par with energy resistance spell until lvl 11, bonus after this, and 60 at lvl20 is quite good enough?)
- +2 (or 3?) spell resistance / char level
- (perhaps +1 initiative / 2 char lvl, not the most useful nor needed)

No sneak attack at all, nor character development feats but still 3 OP abilities.

I would still add a choice to select positive or negative channel at level 1 or 2 (you are a godling after all, and it's not that powerfull in itself).

Changing Signature attack, IE for "Divine Fury" to also add +1 damage/dice on spells (semi bolster, that could augment to +2/dice at level 20), or even upping spells dice size by 1 (rarer (only gold dragon?), more flavourful and less powerful option), could even include the bonus spell pen from up there to have distinct offensive/defensive feature.
At some point allow you to switch damage types to divine (same that the gold dragon thing).

That way the progression would be much more linear.

**Comment by JohN100x1** [comment]
I also think progression pacing should be improved. I'll implement these ideas in 3.0.0 and see if there's anything else that could be changed.
