### ISSUE TITLE
AuraOfRighteousWrathEnchantment  bug or feature, you decide

### ISSUE THREAD

**Issue by kjk001** [JohN100x1/WOTR_IsekaiMod#68]
AuraOfRighteousWrathEnchantment is applied twice on weapons that are both primary and secondary hand equips.
I think only claws grown by an ability are affected, but still they get it twice :D

**Comment by JohN100x1** [comment]
This is a bug. I don't think claws should get the effect applied twice.

**Comment by kjk001** [comment]
it is because they count as both mainhand and offhand,
for the offhand buff it should be possible to add a condition that says and not mainhand which would fix this

**Comment by JohN100x1** [comment]
I noticed in your branch that in `AuraOfRighteousWrathEnchantment`, after replacing `CreateWeaponEnchantment` with `CreateBlueprint<BlueprintWeaponEnchantment>`, that `bp.WeaponFxPrefab = new PrefabLink();` is missing. This might lead to bugs from my experience with null prefab fields in buffs.

**Comment by kjk001** [comment]
Did you figure out the if condition here to prevent it from applying the buff to a secondary hand if it also a main hand?

**Comment by JohN100x1** [comment]
I haven't been able to figure this out. I think I'll keep it as it is for now.

**Comment by kjk001** [comment]
There doesn't seem to be a condtition allowing for an and not condition on the weapons type check.

**Comment by bundillion** [comment]
I've also occasionally had it roll the 5d6 like 40 times (5d6+5d6+5d6...) on a charge attack. Definitely a feature (except that it makes the game seize up for a moment) since it's only happened on allies and animal companions, and I have no idea how to reproduce it reliably. Might be involved with the Pounce ability, though.

**Comment by JohN100x1** [comment]
Since I will be rewroking this feature, I will remove the effect on additional limbs.
