### ISSUE TITLE
Isekai Elf heritages are missing

### ISSUE THREAD

**Issue by SappyforRagnaros** [JohN100x1/WOTR_IsekaiMod#70]
The Isekai elf heritages are missing for me I tried disabling my other mods and creating a new character and it's still missing is anyone else having this issue?

**Comment by kjk001** [comment]
Could you, in the mod manager that pops up after the game loaded, go to logs and there on see detailed log and post the txt file that this opens for us here?

I do not have your exception, but with that file I could check if we can see what might be causing it.

Alternatively a list of all mods you are running would be helpful as the most likely cause is a conflicting blueprint id, and besides your log, the easiest way to verify that would be to start it with all those mods ourself.

Also, please double check if you have the other Isekai Heritages, it could be that your heritage block is disabled as a whole.
That also would be helpful information.

**Comment by SappyforRagnaros** [comment]
I have the other isekai heritages except for elf and gnome heritages, after realizing there are logs, (never noticed) I noticed that the isekai elf traits weren't showing up since tabletop tweaks have their own alternative racial traits, so I disabled those restarted the game and it's working now and thanks.
Also I have toybox, tabletop tweaks, tabletop tweaks reworks, and Isekai mod.

**Comment by kjk001** [comment]
It is still good for us to know that those heritages from tabletop tweaks cause an issue.
If you want to use their custom heritages and the isekai heritages go to the info.json of the Isekai Mod and the following values to the array LoadAfter:
"TabletopTweaks-Core",
    "TabletopTweaks-Base",
    "TabletopTweaks-Reworks",
That ensures that the IsekaiMod will be loaded after them, that way when they delete the array of base values to replace them with their custom choices this is not loaded yet and the Isekai Heritages will instead be added to their already populated array.

PS. Or just wait for the next major release for which I have already blown up that exact LoadAfter Parameter by adding any major mod I could think of ;)
