### ISSUE TITLE
Few legacy ideas

### ISSUE THREAD

**Issue by Nerin3** [JohN100x1/WOTR_IsekaiMod#83]
Kineticist Legacy - Dark Elementalist
Alternative version of Kinetic Lord but uses Dark Elementalist Archetype and int scaling instead.

Genius Legacy - Master of All Trades 
Gives you one additional feat every even level.

Nature Legacy - Nature Mage
Gives you druid's wild shape feature.

Warrior's Legacy - Fighting Spirit 
Basic Fighter into a legacy 

Brawler's Legacy - Fist of a Dragon
Scaled Fist Monk into a legacy

Judge's Legacy - Lawyer Reborn
Gives Inquisitor's abilities. 

Additionally, I think you should limit legacies, so you can only pick them at 1st level, when you choose class for the first time.

**Comment by JohN100x1** [comment]
Great ideas. I think it makes sense to limit the legacies so that the `Legacy Class Feature` and the `Dual Class - Legacy Class Feature` can only be selected once each. I'll see if there's any components that specify a prerequisite "level x or lower", but if not then I'll make a component for it.

**Comment by Nerin3** [comment]
Fighter - Level in IP count as fighter levels for purpose of other feats.
You get Bravery, Weapon Training, Armor Training, Weapon Mastery and Armor Mastery
Monk - You get everything that scaled fist monk gets, except of movement speed and Bonus Feats + instead of [Ki Strike - Lawful] you get to choose if it's Lawful or Chaotic or Good or Evil.
Judge - You get what Inquisitor gets except of Domain and Teamwork feats.

**Comment by ThePiggyGalaxy** [comment]
Please also do something like a chimera for bloodrager bloodlines (melee and shit) and one for the shifter class (if you have the dlc probably), probably with only one or two shapeshifting choices, or heritage choices if you want to go in depth

**Comment by kjk001** [comment]
IP levels already count as fighter levels for purposes of qualifying for other feats. 

I will consider the rest.
Bloodrager bloodline version sounds like something that should only be available to Edge Lords, what do you think @JohN100x1 ?

**Comment by JohN100x1** [comment]
I never played bloodrager before but from [what I read](https://www.d20pfsrd.com/classes/hybrid-classes/Bloodrager/#Bloodrager_Bloodlines) it does seem very melee focused so making it edgelord only makes sense. I had originally intended the villain to be a magic-focus subclass but I think at this moment I've made it too powerful with the amount of OP abilities it has.

**Comment by ThePiggyGalaxy** [comment]
Well, an Bloodrager is supposed to be like a barbarian with enough self control / (innate) talent to be able to cast spells, my biggest thing for it though is that when bloodraging your bloodline manifests in ways that help you in melee sure, but, honestly with even the isekai protag main class (let alone edgelord) they aren't really necessary, bloodrage (with mods) just has awesome feats I want to be able to use as an isekai protag,

on an entirely unrelated note, in character creation with it still available on class selection, i can't seem to find the dread knight legacy in any of the legacy selections? if it's not a mistake on my part, I'll make a separate issue for this

**Comment by Nerin3** [comment]
> I never played bloodrager before but from [what I read](https://www.d20pfsrd.com/classes/hybrid-classes/Bloodrager/#Bloodrager_Bloodlines) it does seem very melee focused so making it edgelord only makes sense. I had originally intended the villain to be a magic-focus subclass but I think at this moment I've made it too powerful with the amount of OP abilities it has.

Instead of nerfing a villain, give him a weakness, because every villain has a weakness. 
Allow player to choose to which element he's vulnerable to and they won't be able to mitigate it with immunities.

**Comment by Nerin3** [comment]
> I never played bloodrager before but from [what I read](https://www.d20pfsrd.com/classes/hybrid-classes/Bloodrager/#Bloodrager_Bloodlines) it does seem very melee focused so making it edgelord only makes sense. I had originally intended the villain to be a magic-focus subclass but I think at this moment I've made it too powerful with the amount of OP abilities it has.

Instead of nerfing amount of op abilities, you could give him a weakness, because every villain has a weakness. 
Allow player to choose to which element he's vulnerable to and they won't be able to mitigate it with immunities. Do the same for one type of physical damage but give him an option to mitigate one of these vulnerabilities.

**Comment by kjk001** [comment]
Yeah the villain is supposed to be a thinker so any kind of rage does not really fit with their modus operandi.

**Comment by kjk001** [comment]
a disatvantage might be an idea, it doesn't even have to be a vulnerability to an element or weapon, it could be something like "Always overthinking things - you always spend the first round evaluating the enemy, no matter how pathetic they are, you always have to consider the trap that might be hidden in every fight before you feel free to act"

**Comment by kjk001** [comment]
hm, is there a way to limit beneficial spells to yourself?
"Inherent distrust - you refuse to truly consider your allies companions and to trust them fully, as such beneficial aoe spells tend to exclude them when cast by you..."

**Comment by JohN100x1** [comment]
> Instead of nerfing amount of op abilities, you could give him a weakness, because every villain has a weakness.
Allow players to choose to which element/physical damage type they are vulnerable to so they take double damage from it are unable to mitigate it with immunities. Do the same for one type of physical damage but give him an option to mitigate one of these vulnerabilities.

@Nerin3
It was just a thought I had, but I realised the irony of making this super unbalanced Isekai protagonist class only to think about how to balance its subclasses. Maybe there isn't really a need to consider a nerf.

> hm, is there a way to limit beneficial spells to yourself?
"Inherent distrust - you refuse to truly consider your allies companions and to trust them fully, as such beneficial aoe spells tend to exclude them when cast by you..."

@kjk001
This sounds like a really huge handicap, and also kind of awkward considering the villain has the `Corrupt Aura` feature which buffs allies. I'm thinking villains could have a selection of tragic "backstories" with disadvantages on a similiar level to oracle curses.

**Comment by kjk001** [comment]
mechanically yes, rp wise there would be at least one villain that it would fit for :D

**Comment by kjk001** [comment]
@Nerin3 Feedback question regarding the scaled fist, is the reason for the scaled fist specifically its slightly draconic abilities or the fact that its ac bonus uses charisma rather than wisdom?
Because patching just that feat as part of the legacy would likely be easier than patching everything subclass dependent...

Someone else had also suggested Overwhelming Soul as a kinetic subclass so I will look at both as options for the next patch.

Bloodrager, I am not sure if it should have a chimera aspect like the sorcerer. But it definitly should be incompatible with sorc legacy if added.

Shifter I am still highly tempted to just mix together with druid for a true shapeshifter.

Ah well I guess I know what I will be spending my weekend on.

**Comment by Nerin3** [comment]
> @Nerin3 Feedback question regarding the scaled fist, is the reason for the scaled fist specifically its slightly draconic abilities or the fact that its ac bonus uses charisma rather than wisdom? Because patching just that feat as part of the legacy would likely be easier than patching everything subclass dependent...
> 
> Someone else had also suggested Overwhelming Soul as a kinetic subclass so I will look at both as options for the next patch.
> 
> Bloodrager, I am not sure if it should have a chimera aspect like the sorcerer. But it definitly should be incompatible with sorc legacy if added.
> 
> Shifter I am still highly tempted to just mix together with druid for a true shapeshifter.
> 
> Ah well I guess I know what I will be spending my weekend on.

It uses charisma and is the most isekaiprotagonist-like out of them. Why be a boring monk when you can be a dragon monk.

**Comment by Nerin3** [comment]
Also there is this mod: https://github.com/alterasc/MicroscopicContentExpansion
Which adds a proper antipaladin, so you could use this one as an alternative to Dread Lord.

**Comment by kjk001** [comment]
Dread Lord and this class are actually fairly identical when it comes to the base class(though it has a more archetypes), but Dread Lord had the nicer pictures for its feats in my opinion...

Archetypes that overrule the base types resource system are a special kind of hell, particulary since the overruling tends to be useless because the new resource and feats tend to do the exact same thing (coughs eldritch scion) only restricted purely to that archetype. That is why I asked regarding the monk as just flipping the one feat that uses charisma rather than wisdom would be easier if the breath weapon is not an essential requirement...

**Comment by Mythalar** [comment]
> Judge - You get what Inquisitor gets except of Domain and Teamwork feats(or merge it with tactician so you get the teamwork feats)

Well, the litteral Judge Archetype can be used, so team feats are excluded and there is a unique judgement aura.

**Comment by Mythalar** [comment]
For one I would let the witch hexes to the Villain if you keep this idea.
There are already various ways to have channel energy without hex channeler and the specific witch hexes could really open the build possibilities for the Villain subclass which is powerful but limited with legacies. And it does give a defining flavor.

**Comment by kjk001** [comment]
> [User](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=122479200) asks:
> 
> > Are you still working on legacies? I'd like to see a Witch legacy, not just Shaman, specifically because if you take Hex Channeler you can't progress its channel ability with shaman hexes, only witch hexes.
> 
> Not sure about this one so I'll leave it for you guys to decide if it's worth to implement.

I don't really  use hex users so I was unaware that there is a big difference in the list of available hexes and their progressions.
I will add it to my current list for 4.3.

**Comment by Mythalar** [comment]
> I don't really use hex users so I was unaware that there is a big difference in the list of available hexes and their progressions. I will add it to my current list for 4.3.

I would integrated this legacy in the Mastermind subclass the same way as I would integrate domain powers to the Gode Emperor to give them a unique theme.
