### ISSUE TITLE
Moar free metamagic choices (integrations)

### ISSUE THREAD

**Issue by ThePiggyGalaxy** [JohN100x1/WOTR_IsekaiMod#86]
In TabletopTweaks Base there are some newly added metamagic feats which do the following:

- Burning Spell (Metamagic)
The acid or fire effects of the affected spell adhere to the creature, causing more damage the next round. When a creature takes acid or fire damage from the affected spell, that creature takes damage equal to 2x the spell’s actual level at the start of its next turn. The damage is acid or fire, as determined by the spell’s descriptor.

- Encouraging Spell (Metamagic)
Any morale bonus granted by an encouraging spell is increased by 1.

- Flaring Spell (Metamagic)
The electricity, fire, or light effects of the affected spell create a flaring that dazzles creatures that take damage from the spell. A flare spell causes a creature that takes fire or electricity damage from the affected spell to become dazzled for a number of rounds equal to the actual level of the spell. A flaring spell only affects spells with a fire, light, or electricity descriptor.

- Intensified Spell (Metamagic)
An intensified spell increases the maximum number of damage dice by 5 levels. You must actually have sufficient caster levels to surpass the maximum in order to benefit from this feat. No other variables of the spell are affected, and spells that inflict damage that is not modified by caster level are not affected by this feat.

- Piercing Spell (Metamagic)
When you cast a piercing spell against a target with spell resistance, it treats the spell resistance of the target as 5 lower than its actual SR.

- Rime Spell (Metamagic)
The frost of your cold spell clings to the target, impeding it for a short time. A rime spell causes creatures that takes cold damage from the spell to become entangled for a number of rounds equal to the original level of the spell.

- Solid Shadows (Metamagic)
When casting a shadow spell, that spell is 20% more real than normal.

- Elemental Spell (Metamagic)
Choose one energy type: acid, cold, electricity, or fire. You may replace a spell’s normal damage with that energy type "or split the spell’s damage, so that half is of that energy type and half is of its normal type.

Please add some of these as automatic feats, since the elemental spell one really complements the other ones it would be ideal if even just the elemental ones get added

**Comment by ThePiggyGalaxy** [comment]
Also wanted to mention that this mod has become somewhat essential to my enjoyment of the game lol, and it's still active development means the world to me

**Comment by JohN100x1** [comment]
I'll think about it. It depends on how hard something like this would be to implement. I would not want to make TabletopTweaks-Base a dependency because unlike TabletopTweaks-Core which has a bunch useful utility methods, TabletopTweaks-Base introduces alot of changes to the game itself.

**Comment by bundillion** [comment]
I'm wondering if it might be easier to make an ability that reduces all spell level increases from metamagic? Then the player has to pick the metamagic feats themselves, but still get the benefits of not having the increase? With the Favored Metamagic ability as a reference, maybe.

**Comment by JohN100x1** [comment]
There are some mechanics in the game that are hardcoded as enums and Favorite Metamagic is one of them. Adding a new favorite metamagic would require me to edit the game mechanics which I have no idea how. All metamagics are basically handled as enums.

I see that TabletopTweaks-Core has a list of [CustomMetamagic](https://github.com/Vek17/TabletopTweaks-Core/blob/master/TabletopTweaks-Core/MechanicsChanges/MetamagicExtention.cs#L27) enums that lists the metamagics from TabletopTweaks-Base which seems very promising. It might be possible to implement without having TabletopTweaks-Base as a dependency.

**Comment by bundillion** [comment]
Ooh! Fingers crossed for the mounting excitement of this development.

**Comment by Mythalar** [comment]
The little QoL of Auto metamagic is also to not have multiple variations of the same spells.
As a spontaneous spell caster with already a quite long spell list that would be a very crowed spell tab !

The "reduce level of all metamagic feats" basically already exists in game with the Trickster Completly normal spell no?

**Comment by JohN100x1** [comment]
I tested some of them and they seem to work. There's quite alot of OP abilities now.

![图片](https://user-images.githubusercontent.com/16169515/226140087-c0fc48ff-29f2-4969-9f17-5348107d8569.png)

**Comment by Mythalar** [comment]
<(꒪▿꒪)>
So much power for my next Villain...
