### ISSUE TITLE
No dread lord Legacy

### ISSUE THREAD

**Issue by ThePiggyGalaxy** [JohN100x1/WOTR_IsekaiMod#87]
**Describe the bug**
When selecting a legacy, the dread lord option does not appear, despite the class it's based on being selectable.

**To Reproduce**
1. Go to class and choose isekai protagonist
2. Click on the legacy choice (you can skip ahead without doing the entirety with toybox)
3. See error

**Expected behavior**
The Dreadlord legacy being visible and choosable

**Screenshots**
![image](https://user-images.githubusercontent.com/85683997/224847545-970c81b8-85d3-4f7e-8918-97f2b1b7eac3.png)
![image](https://user-images.githubusercontent.com/85683997/224847603-129ed1e7-509e-42d8-b802-f624045c6857.png)
![image](https://user-images.githubusercontent.com/85683997/224847671-dba0cdda-8270-457c-bee0-d3edd23864c3.png)
![image](https://user-images.githubusercontent.com/85683997/224847751-2d31bb46-8743-437e-ab92-01914696647f.png)
![image](https://user-images.githubusercontent.com/85683997/224847927-eeddffc4-14fb-4613-ab58-31d075bdc32a.png)

**Additional context**

**Comment by bundillion** [comment]
Do you have Expanded Content installed?

**Comment by JohN100x1** [comment]
I was able find out what the issue was. The [guid reference for one of the dread knight features was wrong](https://github.com/JohN100x1/WOTR_IsekaiMod/pull/85/commits/d625ba31ce44124518995ae97b44de92f1949433), leading to a guard clause causing an early exit when trying to add the dread lord legacy. This fix will come with the 4.1.0 release.

**Comment by kjk001** [comment]
the guid was correct when I made it, I hate this update it broke soo much...

**Comment by Nerin3** [comment]
Well there is also this mod: https://github.com/alterasc/MicroscopicContentExpansion
Which adds a proper antipaladin instead of a partially homebrewed one.
