### ISSUE TITLE
Oracle Legacy Channel Energy bug

### ISSUE THREAD

**Issue by Nerin3** [JohN100x1/WOTR_IsekaiMod#92]
If i choose Oracle based legacy and choose life mystery and then mystery to channel positive energy, the channel energy skill doesn't scale with Isekai Protagonist's level, making it quite useless. I haven't tested it yet, but I reckon this could mean the same for other mysteries/abilities.

**Comment by JohN100x1** [comment]
From what I remember, there are multiple versions of the channel energy ability that scales of a particular class level. The ability would need to be patched to scale of Isekai protagonist class level as well.

**Comment by kjk001** [comment]
the crawler that goes down the tree should add the class everywhere it needs to be. 
But I am guessing that there is yet another special kind of logic just for channel features that needs to be added.
I will fix it.
Also quick question, for reference I looked at the Isekai Protagonist Channel feature and `bp.EffectOnAlly = AbilityEffectOnUnit.Harmful;` seems wrong to me. At least logically...

**Comment by JohN100x1** [comment]
> Also quick question, for reference I looked at the Isekai Protagonist Channel feature and bp.EffectOnAlly = AbilityEffectOnUnit.Harmful; seems wrong to me. At least logically...
You're right. I copy and pasted the damage and healing versions channel energy features and forgot to change this.

**Comment by kjk001** [comment]
quick info: while m_class in ContextRankConfig is an array it does not accept multiple values, everything but the first is ignored.
So the correct way to handle that was to check if it was declared for the reference class on an ability, then if so to add a second ContextRankConfig that copies over everything but the class and add that as a component.

Anyway Bugfix done and locally tested.
