### ISSUE TITLE
Channel energy and Selective channel

### ISSUE THREAD

**Issue by Mythalar** [JohN100x1/WOTR_IsekaiMod#95]
Hey,

Little issue : as a God Emperor with Channel energy (positive) and the feat Selective channel I still cure enemies too.

**Comment by JohN100x1** [comment]
I found out the issue was that the channel energy ability was checking for the selective channel feature on the [targeted creatures rather than the caster](https://github.com/JohN100x1/WOTR_IsekaiMod/commit/77aa4a3fd0ba27920e59a6aa575a11dd3d677939). This should be fixed in 4.2.0.

**Comment by Mythalar** [comment]
Nice, minor thing but can be troublesome ^^
