### ISSUE TITLE
UMM settings UI improvement

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#97]
Here's is a list of changes that would improve the settings UI.
1. Add another tab for options. So we have two tabs in total: added content and settings.
2. Have two Settings groups for the added content tab, `Isekai` and `Other`.
3. Options tab after implementing (#96):
      - `Exclude Companions and Mercenaries from having the Isekai Protagonist Class.`
      - `Allow multiple Mythic Overpowered Abilities to be selected.`
      - `Allow multiple Mythic Special Powers to be selected.`
4. Move `Merge Isekai Spelllist` into options tab.
5. Add UMM option to restrict Exceptional feats, Mythic OP abilities and mythic special powers to the Isekai Protagonist Class (#104)

### Result
![图片](https://user-images.githubusercontent.com/16169515/226219040-adaf097b-7660-4095-bca0-abae362211a5.png)

**Comment by Mythalar** [comment]
Regarding UMM : when I update the mod the merge spell books options reverts back to deactivated whereas the other options are correctly saved.

**Comment by JohN100x1** [comment]
I replaced that option to be use a slightly different variable name. See the new [AddContent.json](https://github.com/JohN100x1/WOTR_IsekaiMod/blob/version-4-2-0/IsekaiMod/Config/AddedContent.json) format.
